name: NoteGoat CI/CD
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      REACT_APP_API_HOST: https://api-dev.notegoatapp.com
    steps:
      - uses: actions/checkout@v2
        with:
          repository: Note-Goat/integration-tests
          ref: main
          ssh-key: ${{ secrets.SSH_KEY }}
      - run: yarn global add jest
      - run: yarn
      - run: yarn test
  Build-And-Deploy:
    needs: Test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      REACT_APP_API_HOST: https://api-dev.notegoatapp.com
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: ./bin/01-build.sh
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - run: S3_BUCKET=dev.notegoatapp.com ./bin/02-deploy.sh
