name: Release To Production
on:
  push:
    tags:
      - 'v*'
jobs:
  Build-And-Deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_HOST: https://api.notegoatapp.com
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: ./bin/01-build.sh
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - run: S3_BUCKET=notegoatapp.com ./bin/02-deploy.sh
